// Package licenses provides functionality for updating licenses metadata in a graph.
// It fetches licenses from a remote source and updates them in the graph.
package licenses

import knowledge "github.com/CodeClarityCE/utility-types/knowledge_db"

func addCodeClarityInfo(licenses []knowledge.License) []knowledge.License {

	for license := range licenses {
		switch licenses[license].LicenseID {
		case "BSD-1-Clause":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'BSD-1-Clause' is a permissive open-source license that allows users to use, modify, and distribute the software under certain conditions. Also known as the 'Simplified BSD License' or 'FreeBSD License,' this license requires that any redistribution of the software includes a copy of the original license and copyright notice. While it permits modification and distribution, it does not compel users to release their modifications under the same license. The BSD-1-Clause license is often chosen by developers who want to share their code while maintaining some level of attribution and liability protection."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "0BSD":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as '0BSD' is a permissive open-source license that allows users to freely use, modify, and distribute software without significant restrictions. It is also sometimes referred to as the 'FreeBSD License' or the 'BSD Zero-Clause License.' The key characteristic of the 0BSD license is that it has no conditions or limitations, essentially granting users unrestricted freedom to do whatever they want with the software. This license is often chosen by developers who want to make their code widely available with minimal restrictions."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "Apache-1.0":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'Apache-1.0' is an open-source license developed by the Apache Software Foundation. It is an older version of the Apache License and has been deprecated in favor of newer versions like Apache-2.0.  The Apache-1.0 license is a permissive open-source license that allows users to use, modify, and distribute the software under certain conditions. It grants users extensive rights and freedoms, including the right to sublicense, modify, and distribute the software, both in source code and compiled form.  The license requires that any redistribution of the software includes the original copyright notice and disclaimers. It also mandates that any modifications made to the software be clearly marked as such.  One notable aspect of the Apache-1.0 license is its explicit liability disclaimer, stating that the software is provided 'as is' without any warranty or liability from the original authors or copyright holders.  While the Apache-1.0 license is still available for historical reference, it is generally recommended to use newer versions like Apache-2.0, which address certain issues and provide more clarity."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "Apache-2.0":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'Apache-2.0' is an open-source license widely used for software distribution. It is developed and maintained by the Apache Software Foundation.  The Apache-2.0 license is a permissive license that allows users to use, modify, and distribute the software under certain conditions. It grants users extensive rights and freedoms, including the right to sublicense, modify, and distribute the software, both in source code and compiled form.  Under the Apache-2.0 license, users are required to include the original copyright notice and license text in all copies of the software. They must also indicate any modifications made to the software.  One notable aspect of the Apache-2.0 license is its explicit patent grant, which gives recipients a license to use any patents held by the contributors for implementing, using, or distributing the software.  The license also includes a comprehensive liability and warranty disclaimer, stating that the software is provided 'as is' without any warranty or liability from the original authors or copyright holders.  The Apache-2.0 license is considered to be a business-friendly license and is widely used in both open-source and commercial projects due to its permissive nature and compatibility with other open-source licenses."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use", "patent-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright", "document-changes"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"trademark-use", "liability", "warranty"}
		case "Apache-1.1":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'Apache-1.1' is an open-source license developed by the Apache Software Foundation. It is an earlier version of the Apache License and has been superseded by subsequent versions like Apache-2.0.  The Apache-1.1 license is a permissive open-source license that allows users to use, modify, and distribute the software under certain conditions. It grants users extensive rights and freedoms, including the right to sublicense, modify, and distribute the software, both in source code and compiled form.  The license requires that any redistribution of the software includes the original copyright notice and disclaimers. It also mandates that any modifications made to the software be clearly marked as such.  One notable aspect of the Apache-1.1 license is its explicit liability disclaimer, stating that the software is provided 'as is' without any warranty or liability from the original authors or copyright holders.  While the Apache-1.1 license is still available for historical reference, it is generally recommended to use newer versions like Apache-2.0, which address certain issues, provide more clarity, and are considered more compatible with other open-source licenses."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright", "document-changes"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "BSD-2-Clause":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'BSD-2-Clause' is a permissive open-source license that allows users to use, modify, and distribute the software under certain conditions. Also referred to as the 'Simplified BSD License' or 'FreeBSD License,' this license requires that any redistribution of the software includes a copy of the original license and copyright notice. It permits modifications and distribution, including in proprietary projects, without mandating that derivative works be released under the same license. The BSD-2-Clause license is often chosen by developers who want to share their code while providing some level of attribution and liability protection."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "BSD-3-Clause":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The software license known as 'BSD-3-Clause' is a permissive open-source license that allows users to use, modify, and distribute the software under certain conditions. Also referred to as the 'Modified BSD License' or 'New BSD License,' this license includes three clauses that outline the terms and obligations. The BSD-3-Clause license requires that any redistribution of the software includes a copy of the original license and copyright notice. It permits modifications and distribution, including in proprietary projects, without mandating that derivative works be released under the same license. Additionally, it includes a clause that disclaims any warranty or liability from the original authors. The BSD-3-Clause license is often chosen by developers who want to share their code while providing some level of attribution, liability protection, and flexibility for both open-source and proprietary use. It strikes a balance between permissiveness and maintaining some level of legal clarity and responsibility."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "ISC":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The ISC license is a permissive open-source license commonly used for software distribution. ISC stands for 'Internet Systems Consortium,' which originally created the license.  The ISC license allows users to freely use, modify, and distribute the software under certain conditions. It is considered a simple and straightforward license with minimal restrictions.  Under the ISC license, users are granted the rights to copy, modify, and distribute the software, including in both open-source and commercial projects. Users are required to include the original copyright notice and permission notice in all copies of the software.  Similar to other permissive licenses, the ISC license does not impose copyleft provisions. This means that users are not obligated to release their modifications or derivative works under the same license.  The ISC license is often chosen for its simplicity and permissive nature, allowing for widespread use and distribution of the software with minimal restrictions."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "MIT":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The MIT license is a permissive open-source license widely used for software distribution. It allows users to freely use, modify, and distribute the software under certain conditions.  Under the MIT license, users are granted the rights to copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software. This license gives users significant freedom and flexibility, allowing them to use the software in both open-source and commercial projects.  One key requirement of the MIT license is the inclusion of the original copyright notice and permission notice in all copies or substantial portions of the software. This ensures that proper attribution is given to the original authors.  Overall, the MIT license is known for its permissive nature, providing users with the freedom to use, modify, and distribute the software with minimal restrictions, while still requiring attribution to the original authors."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "MPL-1.1":
			licenses[license].Details.Classification = "copyleft"
			licenses[license].Details.Description = "The Mozilla Public License 1.1 (MPL 1.1) is an open-source license developed by the Mozilla Foundation. It is an earlier version of the Mozilla Public License and has been superseded by newer versions like MPL 2.0.  The MPL 1.1 is a copyleft license that allows users to use, modify, and distribute the software under certain conditions. It shares similarities with other copyleft licenses, such as the GNU General Public License (GPL), in that it requires modifications and derivative works to be distributed under the same license.  Under the MPL 1.1, if you distribute a modified version of the software, you must make the source code for those modifications available to recipients. The license includes provisions for attribution, requiring that the original copyright notice and disclaimer are retained in all copies of the software.  Additionally, the MPL 1.1 includes specific provisions for patents, stating that contributors grant a royalty-free license to any patents they hold that cover their contributions to the software.  While the MPL 1.1 has been superseded by newer versions, it is still available for historical reference. However, it is generally recommended to use the latest version, MPL 2.0, or consult with legal experts for license selection."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use", "patent-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"disclose-source", "include-copyright", "same-license-file"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"trademark-use", "liability", "warranty"}
		case "MPL-1.0":
			licenses[license].Details.Classification = "copyleft"
			licenses[license].Details.Description = "The Mozilla Public License 1.0 (MPL 1.0) is an open-source license developed by the Mozilla Foundation. It is an earlier version of the Mozilla Public License and has been superseded by newer versions like MPL 2.0.  The MPL 1.0 is a copyleft license that allows users to use, modify, and distribute the software under certain conditions. It shares similarities with other copyleft licenses, such as the GNU General Public License (GPL), in that it requires modifications and derivative works to be distributed under the same license.  Under the MPL 1.0, if you distribute a modified version of the software, you must make the source code for those modifications available to recipients. The license includes provisions for attribution, requiring that the original copyright notice and disclaimer are retained in all copies of the software.  Additionally, the MPL 1.0 includes specific provisions for patents, stating that contributors grant a royalty-free license to any patents they hold that cover their contributions to the software.  While the MPL 1.0 has been superseded by newer versions, it is still available for historical reference. However, it is generally recommended to use the latest version, MPL 2.0, or consult with legal experts for license selection."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use", "patent-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"disclose-source", "include-copyright", "same-license-file"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"trademark-use", "liability", "warranty"}
		case "MPL-2.0":
			licenses[license].Details.Classification = "copyleft"
			licenses[license].Details.Description = "The Mozilla Public License 2.0 (MPL 2.0) is an open-source license that allows users to use, modify, and distribute the software under certain conditions. It is developed and maintained by the Mozilla Foundation.  The MPL 2.0 is a copyleft license that combines elements of both permissive and copyleft licenses. It grants users the freedom to use, modify, and distribute the software, including for commercial purposes. Unlike some other copyleft licenses, it does not require derivative works to be released under the same license.  Under the MPL 2.0, any modifications made to the software must be made available in source code form to recipients. However, the license allows for combining MPL-licensed code with other code under different licenses, as long as the MPL-licensed portions remain under the MPL 2.0 license.  The license requires that the original copyright notice, disclaimer, and a copy of the MPL 2.0 license itself are included in all copies of the software.  The MPL 2.0 also provides explicit patent provisions, stating that if a contributor patents their modifications, they grant a patent license to users of the MPL-licensed software.  Overall, the MPL 2.0 is a flexible and comprehensive license that promotes open-source principles while allowing compatibility with other licenses. It strikes a balance between copyleft provisions and permissive use, modification, and distribution of the software."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use", "patent-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"disclose-source", "include-copyright", "same-license-file"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"trademark-use", "liability", "warranty"}
		case "Unlicense":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The 'Unlicense' is an open-source software license that allows users to do whatever they want with the software without any restrictions. It is sometimes referred to as a 'public domain' dedication. The Unlicense effectively relinquishes all rights and places the software in the public domain, enabling anyone to use, modify, distribute, and even commercialize the software without requiring permission or attribution. This license provides maximum freedom to users and removes most legal barriers associated with traditional copyright restrictions. However, it's worth noting that the Unlicense may not offer the same level of legal certainty and protection as more formal licenses, as it completely disclaims any warranties or liability from the original author or contributors."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		case "WTFPL":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The 'WTFPL' (Do What The F*ck You Want To Public License) is an open-source software license that takes a humorous and permissive approach to licensing. It is known for its relaxed and simple terms, allowing users to do practically anything they want with the software.  Under the WTFPL, users are granted the freedom to use, modify, distribute, and even sell the software without any restrictions. The license explicitly states that there are no conditions or limitations imposed, giving users complete freedom to 'do what the f*ck' they want with the software.  The WTFPL is often chosen by developers who want to express a carefree and permissive attitude towards their software and encourage maximum freedom in its use. However, it's important to note that the WTFPL may not offer the same level of legal certainty and protection as more traditional licenses, and it may not be suitable for all projects or situations."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{}
			licenses[license].Details.LicenseProperties.Limitations = []string{}
		case "X11":
			licenses[license].Details.Classification = "permissive"
			licenses[license].Details.Description = "The X11 license, also known as the MIT License or the MIT/X11 License, is a permissive open-source license used for software distribution. It is named after the X Window System, which popularized the use of this license. The X11 license allows users to freely use, modify, and distribute the software, including in both open-source and commercial projects, with minimal restrictions. It grants users the right to copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software without requiring them to release their modifications under the same license. The license primarily focuses on providing the freedom to use and modify the software without imposing many obligations or restrictions on the user. One notable requirement of the X11 license is the inclusion of the original copyright notice and permission notice in all copies or substantial portions of the software. This ensures that proper attribution is given to the original authors. Overall, the X11 license is a permissive license that allows for broad use and distribution of the software while preserving the original copyright and permission notices."
			licenses[license].Details.LicenseProperties.Permissions = []string{"commercial-use", "distribution", "modifications", "private-use"}
			licenses[license].Details.LicenseProperties.Conditions = []string{"include-copyright"}
			licenses[license].Details.LicenseProperties.Limitations = []string{"liability", "warranty"}
		}
	}

	return licenses

}
